repos:
- repo: https://github.com/pycqa/isort
  rev: 5.12.0
  hooks:
    - id: isort
      name: isort
      entry: isort
      require_serial: true
      language: python
      language_version: python3.10
      types: [python]
      args: [ "--sp=pyproject.toml" ]
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.0.1
  hooks:
    - id: trailing-whitespace  # Trim trailing whitespace
      exclude: ^notebooks/
      args: ["--markdown-linebreak-ext=md"]
    - id: check-yaml  # Attempt to load all yaml files to verify syntax
    - id: check-merge-conflict  # Check for files that contain merge conflict strings
    - id: end-of-file-fixer  # Make sure files end in a newline and only a newline
      exclude_types:
        - text
    - id: fix-encoding-pragma  # Remove the coding pragma: # -*- coding: utf-8 -*-
      args: ["--remove"]
    - id: mixed-line-ending  # Replace or check mixed line ending
      args: ["--fix=lf"]
    - id: check-toml  # check if toml files are parseable
- repo: https://github.com/ambv/black
  rev: 23.1.0
  hooks:
    - id: black
      language_version: python3.10
      args: ["--config=pyproject.toml"]
