# GitHub Actions Workflow: Publish to PyPI
# This workflow automates the process of testing and publishing Py-Astra to PyPI.
# This workflow:
#   1. Runs unit tests using the test.yml workflow
#   2. Publishes the package to PyPI given the unit tests passed

name: Publish to PyPI

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  Run-tests:
    name: Run tests
    uses: ./.github/workflows/test.yml
    secrets: inherit

  Publish-to-PyPi:
    runs-on: ubuntu-latest
    environment: PyPI
    needs:
      - Run-tests

    steps:
    - uses: actions/checkout@v3

    - name: Install Hatch
      run: pip install hatch

    - name: Build package
      run: hatch build

# TODO publish once package ready
#    - name: Publish astra-haystack
#      env:
#        HATCH_INDEX_USER: __token__
#        HATCH_INDEX_AUTH: ${{ secrets.PYPI_ASTRA_HAYSTACK_TOKEN }}
#      run: hatch publish -y